version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: touch local.properties
      - run: ./gradlew test --quiet --build-cache

workflows:
  ci_flow:
    jobs:
      - build-and-test
